server.port=8083

spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/agro_orders_db
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true